### PR TITLE
Easily unpack components to static arrays

### PR DESCRIPTION
**Pull request by jonniedie**
```julia
julia> using ComponentArrays

julia> ca = ComponentArray(a=5, b=[4, 1], c = [1 2; 3 4], d=(a=2, b=[6, 30.0]))
ComponentVector{Float64}(a = 5.0, b = [4.0, 1.0], c = [1.0 2.0; 3.0 4.0], d = (a = 2.0, b = [6.0, 30.0]))

julia> @static_unpack a, b, c, d = ca
ComponentVector{Float64,SubArray...}(a = 2.0, b = [6.0, 30.0])

julia> a
5.0

julia> b
2-element SVector{2, Float64} with indices SOneTo(2):
 4.0
 1.0

julia> c
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 1.0  2.0
 3.0  4.0

julia> d
ComponentVector{Float64,SubArray...}(a = 2.0, b = [6.0, 30.0])
```

### CODE REVIEW

**Comment by jonniediegelman** [comment]
FYI @jondavis847

**Comment by ChrisRackauckas** [comment]
What in this is breaking? This is the only change in the breaking v0.15 release but I don't quite see how it breaks previous behavior.

**Comment by jonniedie** [comment]
Oh geez you're right. Actually nothing. I was kinda just on autopilot from working on things that are in versions >1.0 and forgot that 0.x changes are breaking for versions <1.0. I don't think I can revert it at this point, though, right?

**Comment by ChrisRackauckas** [comment]
yeah no reason to revert, I was just confused.

**Pull request merged**
