### PR TITLE
fix: restructure of tracked component arrays

### PR DESCRIPTION
**Pull request by avik-pal**
still need to test if this fixes the scimlsensitivity issues.

cc @ChrisRackauckas

### CODE REVIEW

**Comment by avik-pal** [comment]
locally verified that this patch fixes our downstream issues

**Comment by avik-pal** [comment]
cc @jonniedie for a review

**Comment by avik-pal** [comment]
@jonniedie bump on this

**Review by jonniedie — APPROVED** [review]
Thanks for this! Sorry to get to it so late.

**Comment by ChrisRackauckas** [comment]
I do have to wonder if it could be helpful to move this to SciML or JuliaArrays. You've been responsive so it hasn't turned into an issue, but it does kind of worry me that this has become a pretty crucial piece of the infrastructure but remains one of the only single maintainer packages. The first page of the PR history there is mostly Avik, Vedant, Lilith, Aayush, and Dhariya putting in PRs for SciML maintenance, so it does look like it has entered this phase of continued maintenance.

**Pull request merged**
