### PR TITLE
Allow ChainRulesCore 1.0

### PR DESCRIPTION
**Pull request by oxinabox**
I haven't actually looked at the code to see if anything else is needed,
lets see what CI says

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
This fails Flux tests after upgrading to ChainRules 1.0, so we definitely have fixes needing to go in here. https://buildkite.com/julialang/flux-dot-jl/builds/1496#7bb3aa82-4fcd-4b7f-a3c9-e3de7006c4fa

**Comment by DhairyaLGandhi** [comment]
Actually, Flux tests are pulling in ComponentArrays@0.10.5 instead of 0.11, so the compat entry and a release would be great @jonniedie

**Comment by DhairyaLGandhi** [comment]
Also tests seem to be pulling an old version of Zygote in CI (v0.4.20 vs v0.6.19). Might be that other compat bounds need to be set.

**Comment by DhairyaLGandhi** [comment]
Could we re run ci here?

**Comment by jonniedie** [comment]
To be honest, I'm not really sure how to troubleshoot this. Running the tests locally in a fresh temp environment doesn't run into any of these problems. I also can't reproduce the Zygote @v0.4.20 thing, even by forcing all of the versions of the other packages to the versions they show in the CI run.

Any ideas?

**Comment by jonniedie** [comment]
Oh, well it looks like that did it. There's a segfault on nightly, but it doesn't seem to have to do with ComponentArrays. Is that a Zygote thing?

**Comment by DhairyaLGandhi** [comment]
I've been seeing it in many places but not sure where it's coming from.

**Comment by jonniedie** [comment]
Okay cool. Well I'll go ahead and merge this then. Nightly's gonna nightly.

**Comment by jonniedie** [comment]
Thanks for doing this @oxinabox. Sorry it took so long for me to get around to merging it.

**Comment by oxinabox** [comment]
no problem.

**Pull request merged**
